/**
 * Script para injetar variáveis de ambiente no build
 * Cria um arquivo com as credenciais que será importado pelo app
 */
const fs = require("fs");
const path = require("path");

const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || "";

console.log("=== Inject Env Script ===");
console.log("SUPABASE_URL exists:", !!SUPABASE_URL);
console.log("SUPABASE_ANON_KEY exists:", !!SUPABASE_ANON_KEY);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("❌ ERRO: Variáveis de ambiente não encontradas!");
  console.error(
    "Certifique-se de que EXPO_PUBLIC_SUPABASE_URL e EXPO_PUBLIC_SUPABASE_ANON_KEY estão definidas.",
  );
  process.exit(1);
}

const configContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/inject-env.js at build time

export const ENV_CONFIG = {
  SUPABASE_URL: "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
};
`;

const outputPath = path.join(
  __dirname,
  "..",
  "src",
  "config",
  "env.generated.ts",
);
const outputDir = path.dirname(outputPath);

// Cria diretório se não existir
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

fs.writeFileSync(outputPath, configContent);
console.log("✅ Arquivo de configuração gerado:", outputPath);
